MAPPING_METADATA_DOMAIN = {
    "B29": {
        "cell_name": "imaging modality",
        "domain": "imaging",
        "subdomain": "imaging modality",
        "ontology": "ncit",
    },
    "B30": {
        "cell_name": "imaging sub-modality",
        "domain": "imaging",
        "subdomain": "imaging submodality",
        "ontology": "ncit",
    },
    "B32": {
        "cell_name": "imaging coverage",
        "domain": "anatomy",
        "subdomain": "imaging coverage",
        "ontology": "uberon",
    },
    "B60": {
        "cell_name": "disease model",
        "domain": "disease",
        "subdomain": "disease model",
        "ontology": "doid",
    },
    "B61": {
        "cell_name": "organ or tissue",
        "domain": "anatomy",
        "subdomain": "organ or tissue",
        "ontology": "uberon",
    },
    "B78": {
        "cell_name": "statistical methods",
        "domain": "analysis_ontology",
        "subdomain": "statistical methods",
        "ontology": "swo",
    },
    "B80": {
        "cell_name": "species",
        "domain": "genomic",
        "subdomain": "species",
        "ontology": "ncit",
    },
    "B81": {
        "cell_name": "strain",
        "domain": "strain",
        "subdomain": "strain",
        "ontology": "efo",
    },
    "B82": {
        "cell_name": "immune status",
        "domain": "phenotype",
        "subdomain": "immune status",
        "ontology": "mp",
    },
    "B90": {
        "cell_name": "genotype",
        "domain": "genomic",
        "subdomain": "genotype",
        "ontology": "ncit",
    },
    "B91": {
        "cell_name": "genetic manipulation",
        "domain": "genomic",
        "subdomain": "genetic manipulation",
        "ontology": "ncit",
    },
    "B101": {
        "cell_name": "drug name",
        "domain": "drugs",
        "subdomain": "drug",
        "ontology": "chebi",
    },
    "B126": {
        "cell_name": "analgesic name",
        "domain": "drugs",
        "subdomain": "analgesic",
        "ontology": "chebi",
    },
    "B132": {
        "cell_name": "drugs",
        "domain": "drugs",
        "subdomain": "anhestetic",
        "ontology": "chebi",
    },
    "B152": {
        "cell_name": "commercial name",
        "domain": "drugs",
        "subdomain": "contrast agent",
        "ontology": "chebi",
    },
    "B158": {
        "cell_name": "route of administration",
        "domain": "experimental_conditions",
        "subdomain": "route administration",
        "ontology": "obi",
    },
    "B140": {
        "cell_name": "tissues collected post-euthanasia",
        "domain": "pathology",
        "subdomain": "tissue excised",
        "ontology": "mpath",
    },
    "B142": {
        "cell_name": "histological procedure",
        "domain": "pathology",
        "subdomain": "histological tissue description",
        "ontology": "mpath",
    },
    "B118": {
        "cell_name": "target organ/tissue",
        "domain": "experimental_conditions",
        "subdomain": "target organ/tissue",
        "ontology": "obi",
    },
    "B137": {
        "cell_name": "method",
        "domain": "experimental_conditions",
        "subdomain": "euthanasia method",
        "ontology": "obi",
    },
    "B162": {
        "cell_name": "identification",
        "domain": "cell_line",
        "subdomain": "cell line name",
        "ontology": "cl",
    },
}

MAPPING_DOMAIN_ONTOLOGY = {
    "disease": "doid",
    "drugs": "chebi",
    "anatomy": "uberon",
    "cell_line": "cl",
    "genomic": "ncit",
    "imaging": "ncit",
    "experimental_conditions": "obi",
    "biological_biomedical_resource": "cmo",
    "pathology": "mpath",
    "phenotype": "mp",
    "radiology": "radlex",
    "analysis_ontology": "swo",
    "strain": "efo",
}